global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'ingestion-service'
    static_configs:
      - targets: ['host.docker.internal:8001']

  - job_name: 'quality-service'
    static_configs:
      - targets: ['host.docker.internal:8002']